Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Internal Server Error: /mailsend
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/middleware/common.py", line 72, in process_request
    urlresolvers.is_valid_path("%s/" % request.path_info, urlconf)):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/mailsend/views.py", line 7, in <module>
    from app_mailsender.models import Feedback
ImportError: No module named app_mailsender.models
Internal Server Error: /mailsend/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/mailsend/views.py", line 48, in feedback
    t = loader.get_template('page_feedback.html')
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: page_feedback.html
Not Found: /
Internal Server Error: /mailsend/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/mailsend/views.py", line 46, in feedback
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'mailsend' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /shop/products/
Not Found: /
Internal Server Error: /mailsend/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/mailsender/urls.py", line 8, in <module>
    url(r'^', include('app_mailsender.urls')),
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named urls
Internal Server Error: /mailsend/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/mailsend/views.py", line 53, in feedback
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 387, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 273, in _populate
    for name in pattern.reverse_dict:
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 285, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /mailsend/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/mailsend/views.py", line 53, in feedback
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 387, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 273, in _populate
    for name in pattern.reverse_dict:
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 285, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import mailsend.views.index. View does not exist in module mailsend.views.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/app_mailsender/views.py", line 11, in index
    t = loader.get_template('page_index.html')
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 276, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 331, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'page_attribute', expected 'endblock'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender/app_mailsender/views.py", line 14, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/kalinin/.virtualenvs/mailsender_project/mailsender_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'video' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
